# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nisarg's Notes
tagline: I need version-controlled notes.
description: >- # this means to ignore newlines until "baseurl:"
  This blog is a collection of my thoughts, observations, processes I follow and research about a topic I've dug deep into. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://snisarg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: snisarg
github_username:  snisarg
linkedin_username: snisarg

show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Google Analytics
google_analytics: UA-143385424-1

social:
  name: Nisarg Shah
  links:
    - https://www.facebook.com/snisarg/
    - https://twitter.com/snisarg
    - https://www.linkedin.com/in/snisarg/
    - https://github.com/snisarg

webmaster_verifications:
  google: MPQto5JJBFYPGw43NoatTSHL4NwDNxhr42Tgr_jtuPg
  bing: 75521632482CC8733EF337A2A0FE1815

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: snisarg-github-io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
